ci:
  autofix_prs: true
  autoupdate_schedule: weekly
  autoupdate_commit_msg: 'chore: pre-commit autoupdate'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-json
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.10.1
  hooks:
  - id: mypy

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.2
  hooks:
  - id: ruff
    args: ["--fix"]
  - id: ruff-format

- repo: https://github.com/pycqa/flake8
  rev: '7.1.0'
  hooks:
  - id: flake8
