name: test-evidence
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  build-sample-project:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Meltano
        run: |
          pip install pipx
          pipx install meltano
      - name: Install Meltano Project
        run: meltano install
      - name: Print Evidence config
        run: meltano config evidence
      - name: Test Evidence Sample Build
        run: meltano invoke evidence build
