name: test-evidence
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  build-sample-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Meltano
        run: |
          pip install pipx
          pipx install meltano
      - name: Install Meltano Project
        run: meltano install
      - name: Print Evidence config
        run: meltano config evidence
      - name: Test Evidence Sample Build
        run: meltano invoke evidence build
